{{- if .Values.ingress.enabled -}}
{{- $fullName := include "frontend.fullname" . -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: frontend
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: "Host(`{{ .Values.global.hostname }}`) && PathPrefix(`/`)"
      services:
        - name: {{ $fullName }}
          port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: frontend-tls
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: "Host(`{{ .Values.global.hostname }}`) && PathPrefix(`/`)"
      services:
        - name: {{ $fullName }}
          port: 80
  tls:
    secretName: {{ .Release.Name }}-cert
{{- end }}
