{{- if .Values.ingress.enabled -}}
{{- $fullName := include "hasura-backend-plus.fullname" . -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: hasura-backend-plus
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: "Host(`hbp.{{ .Values.global.hostname }}`) && PathPrefix(`/`)"
      services:
        - name: {{ $fullName }}
          port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: hasura-backend-plus-tls
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: "Host(`hbp.{{ .Values.global.hostname }}`) && PathPrefix(`/`)"
      services:
        - name: {{ $fullName }}
          port: 80
  tls:
    secretName: {{ $fullName }}-cert
{{- end }}
