
# TODO comment required values, and set 'required': https://helm.sh/docs/howto/charts_tips_and_tricks/#know-your-template-functions
# TODO traefik: redirect http to https when tls is enabled

email: pilou@platyplus.io

global:
  # TODO configmap?
  letsencrypt: production # staging or production
  hostname: tilehuria.platyplus.io    

frontend:
  enabled: true
  image:
    tag: latest
    pullPolicy: Always
  ingress:
    enabled: true

minio:
  enabled: true
  defaultBuckets: tilehuria
  accessKey: 
    password: <minio-access-key>
  secretKey:
    password: <minio-secret-key>

rabbitmq:
  enabled: true
  auth:
    username: user
    password: <secret-rabbitmq-password>

postgresql:
  enabled: true
  image:
    tag: 12.3.0
  postgresqlDatabase: tilehuria
  postgresqlUsername: postgres
  postgresqlPassword: secret-postgresql-password
  servicePort: 5432

hasura:
  enabled: true
  image:
    tag: latest
    pullPolicy: Always
  ingress:
    enabled: true
  hasuraAdminSecret: parent-blahhhhhhh
  jwt:
    algorithm: HS256
    key: 2FK6FD+o0+c7tzabcdefghNDi2yARAAKzQlk9876543214nF7EdAh8s3TwpHwrdWT6R
  env:
    HOOKS_URL: "http://{{ .Release.Name }}-hooks"
    HOOKS_REMOTE_SCHEMA: "http://{{ .Release.Name }}-hooks/graphql"
    EVENT_AOI: "http://{{ .Release.Name }}-hooks/events/area-of-interest"
    EVENT_TILE_SET: "http://{{ .Release.Name }}-hooks/events/tile-set"
  
hasura-backend-plus:
  enabled: true
  image:
    tag: latest
  ingress:
    enabled: true
  env: 
    AUTO_MIGRATE: "false"
    HIBP_ENABLE: "false"
    JWT_CUSTOM_FIELDS: ""

hooks:
  enabled: true
  image:
    tag: latest
    pullPolicy: Always

worker:
  enabled: true
  image:
    tag: latest
    pullPolicy: Always
  
