
email: pilou@platyplus.io

# TODO comment required values, and set 'required': https://helm.sh/docs/howto/charts_tips_and_tricks/#know-your-template-functions
# TODO traefik: redirect http to https when tls is enabled
global:
  hostname: tilehuria.platyplus.io
  minio:
    accessKey: <minio-access-key> # TODO secret
    secretKey: <minio-secret-key> # TODO secret
    defaultBuckets: tilehuria # TODO duplicate - couldn't find a workaround
  postgresql:
    postgresqlDatabase: tilehuria
    postgresqlUsername: postgres
    postgresqlPassword: secret-postgresql-password
    servicePort: 5432
  hasura:
    adminSecret: parent-blahhhhhhh # TODO kubernetes secret
    jwtAlgorithm: HS256
    jwtKey: 2FK6FD+o0+c7tzabcdefghNDi2yARAAKzQlk9876543214nF7EdAh8s3TwpHwrdWT6R

frontend:
  enabled: true
  image:
    tag: latest
    pullPolicy: Always
  ingress:
    enabled: true

minio:
  enabled: true
  defaultBuckets: tilehuria

rabbitmq:
  enabled: true
  auth:
    username: user
    password: <secret-rabbitmq-password> # TODO secret

postgresql:
  enabled: true
  image:
    tag: 12.3.0

hasura:
  enabled: true
  image:
    tag: latest
    pullPolicy: Always
  ingress:
    enabled: true
  env:
    HASURA_GRAPHQL_JWT_SECRET: 
      type: "{{ .Values.global.hasura.jwtAlgorithm }}"
      key: "{{ .Values.global.hasura.jwtKey }}"
      # jwk_url: "http://{{ .Release.Name }}-hasura-backend-plus/auth/jwks"
    HOOKS_URL: "http://{{ .Release.Name }}-hooks"
    HOOKS_REMOTE_SCHEMA: "http://{{ .Release.Name }}-hooks/graphql"
    EVENT_AOI: "http://{{ .Release.Name }}-hooks/events/area-of-interest"
    EVENT_TILE_SET: "http://{{ .Release.Name }}-hooks/events/tile-set"
  
hasura-backend-plus:
  enabled: true
  image:
    tag: latest
  ingress:
    enabled: true
  env: 
  # TODO tls is enabled http/https
  # TODO hard code this variable in the deployment template
    SERVER_URL: "https://{{ .Values.global.hostname }}"
    JWT_ALGORITHM: "{{ .Values.global.hasura.jwtAlgorithm }}"
    JWT_KEY: "{{ .Values.global.hasura.jwtKey }}"
    AUTO_MIGRATE: "false"
    HIBP_ENABLE: "false"
    JWT_CUSTOM_FIELDS: ""

hooks:
  enabled: true
  image:
    tag: latest
    pullPolicy: Always

worker:
  enabled: true
  image:
    tag: latest
    pullPolicy: Always
  
