/** Declaration file generated by dts-gen */

export = mapbox__mbtiles

declare class mapbox__mbtiles {
  constructor(uri: string, callback?: (err: Error, mbtiles: any) => void)

  close(callback: any): void

  createZXYStream(options: any): any

  geocoderCentroid(id: any, zxy: any, callback: any): any

  geocoderDataIterator(type: any): any

  geocoderMigrateDocs(rows: any, callback: any): any

  getGeocoderData(type: any, shard: any, callback: any): any

  getGrid(z: any, x: any, y: any, callback: any): any

  getIndexableDocs(pointer: any, callback: any): any

  getInfo(callback: any): any

  getTile(z: any, x: any, y: any, callback: any): any

  putGeocoderData(type: any, shard: any, data: any, callback: any): any

  putGrid(z: any, x: any, y: any, data: any, callback: any): any

  putInfo(data: any, callback: any): any

  putTile(z: any, x: any, y: any, data: any, callback: any): any

  startWriting(callback: any): any

  stopWriting(callback: any): any

  write(table: any, id: any, row: any, callback: any): any

  static findID(filepath: any, id: any, callback: any): any

  static list(filepath: any, callback: any): any

  static registerProtocols(tilelive: any): void

  static schema: string
}
