apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  serverUrl: "https://{{ .Values.global.hostname }}"
  jwtAlgorithm: {{ .Values.jwtAlgorithm }}
  defaultBuckets: {{ .Values.minio.defaultBuckets }}
  rabbitmq.username: {{ .Values.rabbitmq.auth.username }}