apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-minio
  namespace: default
data:
  defaultBuckets: {{ .Values.minio.defaultBuckets }}
  endpoint: "http://{{ .Release.Name }}-minio:9000"
