---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql
type: Opaque
stringData:
    postgresql-password: {{ required ".Values.postgresql.postgresqlPassword is required" .Values.postgresql.postgresqlPassword }}
    url: {{ (printf "postgres://%s:%s@%s-postgresql:%d/%s" (.Values.postgresql.postgresqlUsername | default "postgres") .Values.postgresql.postgresqlPassword .Release.Name (.Values.postgresql.servicePort |int) (required ".Values.postgresql.postgresqlDatabase is required" .Values.postgresql.postgresqlDatabase))}}
    
