---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql
type: Opaque
stringData:
    postgresql-password: {{ .Values.postgresql.postgresqlPassword }}
    url: {{ (printf "postgres://%s:%s@%s-postgresql:%d/%s" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword .Release.Name (.Values.postgresql.servicePort |int) .Values.postgresql.postgresqlDatabase)}}
    
