apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-rabbitmq
  namespace: default
data:
  endpoint: "http://{{ .Release.Name }}-minio:9000"
  username: {{ .Values.rabbitmq.auth.username | default "user" }}