---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
    hasuraAdminSecret: {{ .Values.hasuraAdminSecret }}
    databaseUrl: {{ (printf "postgres://%s:%s@%s-postgresql:%d/%s" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword .Release.Name (.Values.postgresql.servicePort |int) .Values.postgresql.postgresqlDatabase)}}
    jwtKey: {{ .Values.jwtKey }}
    # TODO: scrappy, but it works
    jwtSecret: {{ printf "{\"type\": \"%s\", \"key\": \"%s\"}" .Values.jwtAlgorithm .Values.jwtKey | squote | replace "\\\"" "\"" }}
    
