apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-hasura
  namespace: default
data:
  jwt.algorithm: {{ .Values.jwt.algorithm | default "HS256" }}
  endpoint: "http://{{ .Release.Name }}-hasura/v1/graphql"
