---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-hasura
type: Opaque
stringData:
    hasuraAdminSecret: {{ .Values.hasuraAdminSecret }}
    jwt.key: {{ .Values.jwt.key }}
    # scrappy, but it works
    jwt.secret: {{ printf "{\"type\": \"%s\", \"key\": \"%s\"}" .Values.jwt.algorithm .Values.jwt.key | squote | replace "\\\"" "\"" }}
    
