---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-hasura
type: Opaque
stringData:
    hasuraAdminSecret: {{ required ".Values.hasuraAdminSecret is required" .Values.hasuraAdminSecret }}
    {{- if empty .Values.jwt }}
    {{ fail "A valid .Values.jwt is required."}}
    {{- end -}}
    {{ $algo := .Values.jwt.algorithm  | default "HS256" }}
    {{ $key := required ".Values.jwt.key is required" .Values.jwt.key}}
    jwt.key: {{ $key }}
    # scrappy, but it works
    jwt.secret: {{ printf "{\"type\": \"%s\", \"key\": \"%s\"}" $algo $key | squote | replace "\\\"" "\"" }}
    
